using Asp.Versioning;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Services.API.Controllers;

[ApiController]
[Route("api/[controller]")]
[ApiVersion(1.0)]
[Authorize]
public class InvoicesController : ControllerBase
{
    private readonly ILogger<InvoicesController> _logger;

    public InvoicesController(ILogger<InvoicesController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public async Task<IActionResult> GetInvoices([FromQuery] string? date, [FromQuery] string? companyId)
    {
        _logger.LogInformation("Getting invoices for date: {Date}, company: {CompanyId}", date, companyId);
        return Ok(new List<object>());
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetInvoice(string id)
    {
        _logger.LogInformation("Getting invoice: {Id}", id);
        return Ok(new { id });
    }

    [HttpPost]
    public async Task<IActionResult> CreateInvoice([FromBody] CreateInvoiceRequest request)
    {
        _logger.LogInformation("Creating invoice for customer: {CustomerId}", request.CustomerId);
        return CreatedAtAction(nameof(GetInvoice), new { id = "new-id" }, request);
    }

    [HttpPost("{id}/payments")]
    public async Task<IActionResult> AddPayment(string id, [FromBody] AddPaymentRequest request)
    {
        _logger.LogInformation("Adding payment to invoice: {InvoiceId}, amount: {Amount}", id, request.Amount);
        return Ok(new { success = true });
    }

    /// <summary>
    /// Get auto-generated invoice number
    /// </summary>
    [HttpGet("autogenerated-number")]
    [ProducesResponseType(200)]
    public async Task<IActionResult> GetAutoGeneratedInvoice([FromQuery] string companyId, [FromQuery] bool isInvoice)
    {
        _logger.LogInformation("Getting auto-generated invoice number for company: {CompanyId}", companyId);
        return Ok(new { InvoiceNo = "INV-0001" });
    }

    /// <summary>
    /// Convert estimate to invoice
    /// </summary>
    [HttpPost("{id}/convert-to-invoice")]
    [ProducesResponseType(200)]
    public async Task<IActionResult> ConvertEstimateToInvoice(
        string id, 
        [FromQuery] string modifiedBy, 
        [FromQuery] string companyId)
    {
        _logger.LogInformation("Converting estimate to invoice: {InvoiceId}", id);
        return Ok(new { IsValid = true, Message = "Converted" });
    }

    /// <summary>
    /// Edit invoice
    /// </summary>
    [HttpPut("{id}/edit")]
    [ProducesResponseType(200)]
    public async Task<IActionResult> EditInvoice(string id, [FromBody] object request)
    {
        _logger.LogInformation("Editing invoice: {InvoiceId}", id);
        return Ok(new { IsValid = true, Message = "Updated" });
    }
}

public record CreateInvoiceRequest(string CompanyID, string CustomerId, decimal Total, List<InvoiceItemRequest> Items);
public record InvoiceItemRequest(string Name, decimal Price, int Quantity);
public record AddPaymentRequest(decimal Amount, string Type, string Source);

